export { default as Home } from './Home'
export { default as Work } from './Work'
export { default as Services } from './Services'
export { default as Contact } from './Contact'
export { default as Custom404 } from './404'